#!/bin/sh /etc/rc.common

START=71

start() {
  cp /lib/wifi/mac80211.sh /tmp/
  /root/mac80211_uci.lua > /lib/wifi/mac80211.sh
  rm -f /root/mac80211_uci.lua
  rm -f /etc/rc.d/S71wificonfig-enablemesh
}

stop() {
  echo stop
}
