#!/bin/sh /etc/rc.common

START=72

start() {
  cp  /usr/lib/lua/luci/model/cbi/admin_network/wifi.lua /tmp/wifi.lua.meshadd
  /root/luci_mesh.lua > /usr/lib/lua/luci/model/cbi/admin_network/wifi.lua
  rm -f /root/luci_mesh.lua
  rm -f /etc/rc.d/S72wificonfig-lucimesh
}

stop() {
  echo stop
}
