#!/bin/sh /etc/rc.common

START=73

start() {
  cp  /usr/lib/lua/luci/model/cbi/admin_network/wifi.lua /tmp/wifi.lua.meshaddauthsae
  /root/luci_mesh_authsae.lua > /usr/lib/lua/luci/model/cbi/admin_network/wifi.lua
  rm -f /root/luci_mesh_authsae.lua
  rm -f /etc/rc.d/S73wificonfig-lucimeshauthsae
}

stop() {
  echo stop
}
